name: Trigger Webhook on PR Ready for Review

on:
  pull_request:
    types: [ready_for_review, opened]

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Webhook
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://app.windmill.dev/api/w/windmill-labs/jobs/run/f/f/docs/new_pr'
          method: 'POST'
          contentType: 'application/json'
          customHeaders: |
            {
              "Authorization": "Bearer QfrOKeyXeSHT7C3IgZYF3WnBrssRokxN",
              "Content-Type": "application/json"
            }
          data: |
            {
              "author": "${{ github.event.pull_request.user.login }}",
              "title": "${{ github.event.pull_request.title }}",
              "number": "${{ github.event.pull_request.number }}"
            }